### ISSUE TITLE
Corregir fórmula para "Tonelaje de variación TM"

### ISSUE THREAD

**Issue by EduenSarceno** [EduenSarceno/mc-issues#9]
Fórmula actual:

```
TonelajeOriginal - TonelajeFinal
```

Fórmula deseada:

```
TonelajeFinal - TonelajeOriginal
```

**Comment by elopezv7** [comment]
@EduenSarceno  hola, puedes por favor subir el resto de incidencias que trabajarás esta semana para tener visibilidad? gracias!
